### ISSUE TITLE
普通面向对象的编程方法

### ISSUE THREAD

**Issue by lenxuelenxue** [ziyi2/JQuery#1]
var o = Obj();   应该是  var o =new  Obj(); 吧？

**Comment by lenxuelenxue** [comment]
(三)、`context`具体使用案例（重点,加速查找DOM元素）
//$('strong',this)因为指定了上下文,则通过jQuery的.find()方法查找,因此等价于$('strong').find('h1')   。 应该是等价于$('h1').find('strong')

**Comment by ziyi2** [comment]
> var o = Obj(); 应该是 var o =new Obj(); 吧？

感谢指正，https://github.com/ziyi2/jQuery/commit/8c211730118d96d15a8459003d8e552557b17527
